version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_NAME=henrich
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=henrich
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/henrich.sql:/docker-entrypoint-initdb.d/henrich.sql

volumes:
  mysql_data:
